/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import src.state.GameMenu;

public class App {
    public static void main(String[] args){
        // new Thread(new GameLoop(new Game(699, 700))).start();
        new GameMenu();
    }
}
